apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: demo-latest-2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: demo-latest-2
    app.kubernetes.io/part-of: purple-mermaid-app
  name: demo-latest-2
  namespace: sbudhwar-1
spec:
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: demo-latest-2
    weight: 100
status: {}
